name: Generate release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  generate-release:
    name: Generate release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set the release version
        id: release
        shell: bash
        run: |
          RELEASE_VERSION=${GITHUB_REF:11}

          IS_PRERELEASE=false
          if [[ "$RELEASE_VERSION" == *dev* ]]; then
              IS_PRERELEASE=true
          fi

          {
            echo "release_version=${RELEASE_VERSION}"
            echo "is_prerelease=${IS_PRERELEASE}"
          } >> "$GITHUB_OUTPUT"

          echo "::notice::Release version: ${RELEASE_VERSION}"
          echo "::notice::Is prerelease: ${IS_PRERELEASE}"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: fugit/configs/cliff.toml
          args: -vv --latest --no-exec --github-repo ${{ github.repository }} --strip all
        env:
          GIT_CLIFF__REMOTE__GITHUB__OWNER: toggle-corp
          GIT_CLIFF__REMOTE__GITHUB__REPO: toggle-django-utils

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "v${{ steps.release.outputs.release_version }}"
          prerelease: ${{ steps.release.outputs.is_prerelease }}
          body: ${{ steps.git-cliff.outputs.content }}
